### ISSUE TITLE
Placeholder in logger "Network error" message is not replaced

### ISSUE THREAD

**Issue by xofe** [gorhill/uMatrix#945]
When an asset can't be downloaded, the message "Network error: Unable to connect to {{url}}" is shown in the logger with the `{{url}}` placeholder not replaced by the URL that failed to load. This is due to the [line 104 of src/js/assets.js](https://github.com/gorhill/uMatrix/blob/2cf4a57/src/js/assets.js#L104) trying to replace `{{msg}}` instead of `{{url}}`.

I reported a similar issue a while ago for uBO (https://github.com/gorhill/uBlock/issues/2921), which you understandably closed as an external translation issue, but for uMatrix this affects every language (including English) so seems like something that should be fixed in uMatrix itself.

**Comment by gorhill** [comment]
Fixed in fe995d2bc8e5.

**Comment by uBlock-user** [comment]
Bug is back in 1.4.1b3, block any HOSTS list url and check the logger for that msg.
